server:
  port: 8081
spring:
  application:
    name: payment-service
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:payment-db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.github.rodmotta.payment_service.event.OrderEvent
        spring.json.trusted.packages: com.github.rodmotta.*
        spring.json.use.type.headers: false
