server:
  port: 8080
spring:
  application:
    name: order-service
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:order-db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
